---
- hosts: bootstrap
  user: root
  vars_files:
    - vars/global.yml
    - vars/cobbler.yml
    - vars/ovirt.yml
    - vars/private.yml
  tasks:
    - include: "{{ tasks }}/common.yml"
    - include: "{{ tasks }}/centos.yml"
    - include: "{{ tasks }}/setup-cobbler.yml"
  handlers:
    - include: "{{ handlers }}"
