---
- hosts: bootstrap
  user: root
  vars_files:
    - vars/global.yml
    - vars/idm-client.yml
    - vars/gluster.yml
    - vars/private.yml
  tasks:
    - include: "{{ tasks }}/common.yml"
    - include: "{{ tasks }}/centos.yml"
    #- include: "{{ tasks }}/idm-client.yml"
    #- include: "{{ tasks }}/setup-gluster.yml"
  handlers:
    - include: "{{ handlers }}"
