---
- yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present

- yum: name=epel-release state=latest

- yum: name={{ item }} state=present
  with_items:
    - python-ethtool
    - koan
