---
- newovirt:
    instance_name: bootstrap
    vmname: bootstrap
    resource_type: new
    instance_type: server
    user: "{{ ovirt_user }}"
    password: "{{ ovirt_password }}"
    url: "{{ ovirt_api_uri }}"
    zone: "{{ ovirt_zone }}"
    region: "{{ ovirt_region }}"
    instance_cpus: "{{ instance_cpus }}"
    instance_nic: "{{ instance_nic }}"
    instance_network: "{{ ovirt_network }}"
    instance_disksize: "{{ instance_disksize }}"
    instance_mem: "{{ instance_mem }}"
    disk_alloc: preallocated
    sdomain: "{{ ovirt_storage_domain }}"
    instance_cores: 1
    instance_os: "{{ instance_os }}"
    disk_int: virtio