---
- yum: name="{{ item }}" state=latest
  with_items:
    - cobbler
    - cobbler-web
    - httpd
    - dhcp

- service: name=cobblerd state=started enabled=yes
- service: name=httpd state=started enabled=yes

- command: cobbler get-loaders
- command: cobbler sync

- service: name=dhcpd state=started enabled=yes

- firewalld: service=http permanent=true state=enabled
  notify: reload firewalld
- firewalld: service=https permanent=true state=enabled
  notify: reload firewalld
- firewalld: service=dhcp permanent=true state=enabled
  notify: reload firewalld
- firewalld: service=tftp permanent=true state=enabled
  notify: reload firewalld
- firewalld: port=25151/tcp permanent=true state=enabled
  notify: reload firewalld
